"""Initial schema

Revision ID: 1aabc66480ab
Revises: 
Create Date: 2026-09-07 13:42:04.651787

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1aabc66480ab'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_log_retention_days', sa.Integer(), nullable=True),
    sa.Column('dashboard_trends_retention_days', sa.Integer(), nullable=True),
    sa.Column('honeypot_update_run_retention_days', sa.Integer(), nullable=True),
    sa.Column('monitoring_history_retention_days', sa.Integer(), nullable=True),
    sa.Column('ldap_enabled', sa.Boolean(), nullable=False),
    sa.Column('ldap_server_uri', sa.String(length=255), nullable=True),
    sa.Column('ldap_use_starttls', sa.Boolean(), nullable=False),
    sa.Column('ldap_bind_dn', sa.String(length=255), nullable=True),
    sa.Column('ldap_bind_password_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('ldap_user_search_base', sa.String(length=255), nullable=True),
    sa.Column('ldap_user_search_filter', sa.String(length=255), nullable=False),
    sa.Column('ldap_connect_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('ldap_tls_verify', sa.Boolean(), nullable=False),
    sa.Column('oidc_enabled', sa.Boolean(), nullable=False),
    sa.Column('oidc_issuer_url', sa.String(length=500), nullable=True),
    sa.Column('oidc_client_id', sa.String(length=255), nullable=True),
    sa.Column('oidc_client_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('oidc_username_claim', sa.String(length=100), nullable=False),
    sa.Column('oidc_scopes', sa.String(length=255), nullable=False),
    sa.Column('syslog_enabled', sa.Boolean(), nullable=False),
    sa.Column('syslog_host', sa.String(length=255), nullable=True),
    sa.Column('syslog_port', sa.Integer(), nullable=False),
    sa.Column('syslog_protocol', sa.Enum('udp', 'tcp', 'tls', name='syslog_protocol'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('audit_chain_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_chain_state'))
    )
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.Enum('success', 'denied', 'failure', name='audit_outcome'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('target_label', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log_entries')),
    sa.UniqueConstraint('sequence', name=op.f('uq_audit_log_entries_sequence'))
    )
    op.create_index(op.f('ix_audit_log_entries_action'), 'audit_log_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_created_at'), 'audit_log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entry_hash'), 'audit_log_entries', ['entry_hash'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('name', name=op.f('uq_companies_name'))
    )
    op.create_table('pending_honeypots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('reported_hostname', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('kernel_version', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disks', sa.JSON(), nullable=True),
    sa.Column('source_ip', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_honeypots'))
    )
    op.create_table('ssh_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('pending_public_key', sa.Text(), nullable=True),
    sa.Column('pending_private_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('pending_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('pending_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ssh_identity'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('company_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('honeypot_count', sa.Integer(), nullable=False),
    sa.Column('honeypots_online', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('honeypots_reachable', sa.Integer(), nullable=False),
    sa.Column('needs_updates', sa.Integer(), nullable=False),
    sa.Column('needs_security_updates', sa.Integer(), nullable=False),
    sa.Column('needs_reboot', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_snapshots_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_snapshots')),
    sa.UniqueConstraint('company_id', 'snapshot_date', name='uq_company_snapshot')
    )
    op.create_index(op.f('ix_company_snapshots_company_id'), 'company_snapshots', ['company_id'], unique=False)
    op.create_table('honeypots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('auth_method', sa.Enum('ssh_key', 'password', name='auth_method'), nullable=True),
    sa.Column('secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('host_key_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('runbook', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('discovered_hostname', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('kernel_version', sa.String(length=255), nullable=True),
    sa.Column('cpu_architecture', sa.String(length=64), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('ram_bytes', sa.BigInteger(), nullable=True),
    sa.Column('ram_speed_mhz', sa.Integer(), nullable=True),
    sa.Column('os_id', sa.String(length=64), nullable=True),
    sa.Column('disks', sa.JSON(), nullable=True),
    sa.Column('reboot_required', sa.Boolean(), nullable=True),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=True),
    sa.Column('filesystems', sa.JSON(), nullable=True),
    sa.Column('network_interfaces', sa.JSON(), nullable=True),
    sa.Column('facts_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reachable', sa.Boolean(), nullable=True),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reachability_check_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('facts_refresh_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('monitoring_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('monitoring_history_retention_days', sa.Integer(), nullable=True),
    sa.Column('monitoring_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('services_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('readiness_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('readiness_missing', sa.JSON(), nullable=True),
    sa.Column('upgradable_count', sa.Integer(), nullable=True),
    sa.Column('security_upgradable_count', sa.Integer(), nullable=True),
    sa.Column('flatpak_upgradable_count', sa.Integer(), nullable=True),
    sa.Column('snap_upgradable_count', sa.Integer(), nullable=True),
    sa.Column('updates_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apt_upgradable_packages', sa.JSON(), nullable=True),
    sa.Column('flatpak_upgradable_packages', sa.JSON(), nullable=True),
    sa.Column('snap_upgradable_packages', sa.JSON(), nullable=True),
    sa.Column('packages_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ip', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingest_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_honeypots_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypots')),
    sa.UniqueConstraint('ingest_token_hash', name=op.f('uq_honeypots_ingest_token_hash'))
    )
    op.create_index(op.f('ix_honeypots_company_id'), 'honeypots', ['company_id'], unique=False)
    op.create_index(op.f('ix_honeypots_is_active'), 'honeypots', ['is_active'], unique=False)
    op.create_index(op.f('ix_honeypots_last_seen_at'), 'honeypots', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_honeypots_name'), 'honeypots', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('auth_provider', sa.Enum('local', 'ldap', 'oidc', name='auth_provider'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.Enum('read', 'read_write', name='access_level'), nullable=True),
    sa.Column('totp_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_superadmin AND company_id IS NULL AND access_level IS NULL) OR (NOT is_superadmin AND company_id IS NOT NULL AND access_level IS NOT NULL)', name=op.f('ck_users_superadmin_xor_company_scope')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('honeypot_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('honeypot_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_honeypot_events_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['honeypot_id'], ['honeypots.id'], name=op.f('fk_honeypot_events_honeypot_id_honeypots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_events'))
    )
    op.create_index(op.f('ix_honeypot_events_company_id'), 'honeypot_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_honeypot_events_event_type'), 'honeypot_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_honeypot_events_honeypot_id'), 'honeypot_events', ['honeypot_id'], unique=False)
    op.create_index(op.f('ix_honeypot_events_occurred_at'), 'honeypot_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_honeypot_events_src_ip'), 'honeypot_events', ['src_ip'], unique=False)
    op.create_table('honeypot_monitoring_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('honeypot_id', sa.Uuid(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('load1', sa.Float(), nullable=True),
    sa.Column('load5', sa.Float(), nullable=True),
    sa.Column('load15', sa.Float(), nullable=True),
    sa.Column('ram_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('ram_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('network_io', sa.JSON(), nullable=True),
    sa.Column('disk_io', sa.JSON(), nullable=True),
    sa.Column('filesystems', sa.JSON(), nullable=True),
    sa.Column('failed_services_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['honeypot_id'], ['honeypots.id'], name=op.f('fk_honeypot_monitoring_samples_honeypot_id_honeypots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_monitoring_samples'))
    )
    op.create_index(op.f('ix_honeypot_monitoring_samples_honeypot_id'), 'honeypot_monitoring_samples', ['honeypot_id'], unique=False)
    op.create_index('ix_honeypot_monitoring_samples_honeypot_id_sampled_at', 'honeypot_monitoring_samples', ['honeypot_id', 'sampled_at'], unique=False)
    op.create_table('honeypot_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('honeypot_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('apt', 'flatpak', 'snap', name='package_source'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('held', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['honeypot_id'], ['honeypots.id'], name=op.f('fk_honeypot_packages_honeypot_id_honeypots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_packages'))
    )
    op.create_index(op.f('ix_honeypot_packages_honeypot_id'), 'honeypot_packages', ['honeypot_id'], unique=False)
    op.create_index('ix_honeypot_packages_honeypot_id_source', 'honeypot_packages', ['honeypot_id', 'source'], unique=False)
    op.create_table('honeypot_reachability_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('honeypot_id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['honeypot_id'], ['honeypots.id'], name=op.f('fk_honeypot_reachability_samples_honeypot_id_honeypots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_reachability_samples'))
    )
    op.create_index(op.f('ix_honeypot_reachability_samples_honeypot_id'), 'honeypot_reachability_samples', ['honeypot_id'], unique=False)
    op.create_index('ix_honeypot_reachability_samples_honeypot_id_checked_at', 'honeypot_reachability_samples', ['honeypot_id', 'checked_at'], unique=False)
    op.create_table('honeypot_services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('honeypot_id', sa.Uuid(), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=False),
    sa.Column('load_state', sa.String(length=32), nullable=False),
    sa.Column('active_state', sa.String(length=32), nullable=False),
    sa.Column('sub_state', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['honeypot_id'], ['honeypots.id'], name=op.f('fk_honeypot_services_honeypot_id_honeypots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_services'))
    )
    op.create_index(op.f('ix_honeypot_services_honeypot_id'), 'honeypot_services', ['honeypot_id'], unique=False)
    op.create_index('ix_honeypot_services_honeypot_id_active_state', 'honeypot_services', ['honeypot_id', 'active_state'], unique=False)
    op.create_table('honeypot_tags',
    sa.Column('honeypot_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['honeypot_id'], ['honeypots.id'], name=op.f('fk_honeypot_tags_honeypot_id_honeypots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_honeypot_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('honeypot_id', 'tag_id', name=op.f('pk_honeypot_tags'))
    )
    op.create_table('honeypot_update_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('honeypot_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('strategy', sa.Enum('dist_upgrade', 'full_upgrade', name='upgrade_strategy'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='update_run_status'), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['honeypot_id'], ['honeypots.id'], name=op.f('fk_honeypot_update_runs_honeypot_id_honeypots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_update_runs'))
    )
    op.create_index('ix_honeypot_update_runs_batch_id', 'honeypot_update_runs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_honeypot_update_runs_honeypot_id'), 'honeypot_update_runs', ['honeypot_id'], unique=False)
    op.create_table('saved_honeypot_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('query_string', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_honeypot_views_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_honeypot_views')),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_honeypot_views_user_id_name')
    )
    op.create_index(op.f('ix_saved_honeypot_views_user_id'), 'saved_honeypot_views', ['user_id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('action_params', sa.JSON(), nullable=True),
    sa.Column('target_type', sa.Enum('honeypot', 'company', 'all_honeypots', name='schedule_target_type'), nullable=False),
    sa.Column('target_honeypot_id', sa.Uuid(), nullable=True),
    sa.Column('owner_company_id', sa.Uuid(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_company_id'], ['companies.id'], name=op.f('fk_scheduled_tasks_owner_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_honeypot_id'], ['honeypots.id'], name=op.f('fk_scheduled_tasks_target_honeypot_id_honeypots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks'))
    )
    op.create_index(op.f('ix_scheduled_tasks_next_run_at'), 'scheduled_tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_owner_company_id'), 'scheduled_tasks', ['owner_company_id'], unique=False)
    op.create_table('totp_recovery_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_totp_recovery_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_totp_recovery_codes'))
    )
    op.create_index(op.f('ix_totp_recovery_codes_user_id'), 'totp_recovery_codes', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('backed_up', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_webauthn_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webauthn_credentials')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_webauthn_credentials_credential_id'))
    )
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_totp_recovery_codes_user_id'), table_name='totp_recovery_codes')
    op.drop_table('totp_recovery_codes')
    op.drop_index(op.f('ix_scheduled_tasks_owner_company_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_next_run_at'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_saved_honeypot_views_user_id'), table_name='saved_honeypot_views')
    op.drop_table('saved_honeypot_views')
    op.drop_index(op.f('ix_honeypot_update_runs_honeypot_id'), table_name='honeypot_update_runs')
    op.drop_index('ix_honeypot_update_runs_batch_id', table_name='honeypot_update_runs')
    op.drop_table('honeypot_update_runs')
    op.drop_table('honeypot_tags')
    op.drop_index('ix_honeypot_services_honeypot_id_active_state', table_name='honeypot_services')
    op.drop_index(op.f('ix_honeypot_services_honeypot_id'), table_name='honeypot_services')
    op.drop_table('honeypot_services')
    op.drop_index('ix_honeypot_reachability_samples_honeypot_id_checked_at', table_name='honeypot_reachability_samples')
    op.drop_index(op.f('ix_honeypot_reachability_samples_honeypot_id'), table_name='honeypot_reachability_samples')
    op.drop_table('honeypot_reachability_samples')
    op.drop_index('ix_honeypot_packages_honeypot_id_source', table_name='honeypot_packages')
    op.drop_index(op.f('ix_honeypot_packages_honeypot_id'), table_name='honeypot_packages')
    op.drop_table('honeypot_packages')
    op.drop_index('ix_honeypot_monitoring_samples_honeypot_id_sampled_at', table_name='honeypot_monitoring_samples')
    op.drop_index(op.f('ix_honeypot_monitoring_samples_honeypot_id'), table_name='honeypot_monitoring_samples')
    op.drop_table('honeypot_monitoring_samples')
    op.drop_index(op.f('ix_honeypot_events_src_ip'), table_name='honeypot_events')
    op.drop_index(op.f('ix_honeypot_events_occurred_at'), table_name='honeypot_events')
    op.drop_index(op.f('ix_honeypot_events_honeypot_id'), table_name='honeypot_events')
    op.drop_index(op.f('ix_honeypot_events_event_type'), table_name='honeypot_events')
    op.drop_index(op.f('ix_honeypot_events_company_id'), table_name='honeypot_events')
    op.drop_table('honeypot_events')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_index(op.f('ix_honeypots_name'), table_name='honeypots')
    op.drop_index(op.f('ix_honeypots_last_seen_at'), table_name='honeypots')
    op.drop_index(op.f('ix_honeypots_is_active'), table_name='honeypots')
    op.drop_index(op.f('ix_honeypots_company_id'), table_name='honeypots')
    op.drop_table('honeypots')
    op.drop_index(op.f('ix_company_snapshots_company_id'), table_name='company_snapshots')
    op.drop_table('company_snapshots')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('ssh_identity')
    op.drop_table('pending_honeypots')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_log_entries_entry_hash'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_created_at'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_action'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_table('audit_chain_state')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
