"""per-rule notification wording, drop global templates

Revision ID: 384c2557115e
Revises: 4edc297d7111
Create Date: 2026-09-14 08:08:31.908965

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '384c2557115e'
down_revision: str | None = '4edc297d7111'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - wrapped to this project's
    # 100-col limit ###
    op.drop_column('app_settings', 'notification_unavailable_body')
    op.drop_column('app_settings', 'notification_alert_body')
    op.drop_column('app_settings', 'notification_unavailable_subject')
    op.drop_column('app_settings', 'notification_recovered_subject')
    op.drop_column('app_settings', 'notification_alert_subject')
    op.drop_column('app_settings', 'notification_recovered_body')
    op.add_column(
        'notification_rules', sa.Column('alert_subject', sa.String(length=255), nullable=True)
    )
    op.add_column('notification_rules', sa.Column('alert_body', sa.Text(), nullable=True))
    op.add_column(
        'notification_rules',
        sa.Column('unavailable_subject', sa.String(length=255), nullable=True),
    )
    op.add_column('notification_rules', sa.Column('unavailable_body', sa.Text(), nullable=True))
    op.add_column(
        'notification_rules', sa.Column('recovered_subject', sa.String(length=255), nullable=True)
    )
    op.add_column('notification_rules', sa.Column('recovered_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - wrapped to this project's
    # 100-col limit ###
    op.drop_column('notification_rules', 'recovered_body')
    op.drop_column('notification_rules', 'recovered_subject')
    op.drop_column('notification_rules', 'unavailable_body')
    op.drop_column('notification_rules', 'unavailable_subject')
    op.drop_column('notification_rules', 'alert_body')
    op.drop_column('notification_rules', 'alert_subject')
    op.add_column(
        'app_settings',
        sa.Column(
            'notification_recovered_body', sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        'app_settings',
        sa.Column(
            'notification_alert_subject',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'app_settings',
        sa.Column(
            'notification_recovered_subject',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'app_settings',
        sa.Column(
            'notification_unavailable_subject',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'app_settings',
        sa.Column('notification_alert_body', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'app_settings',
        sa.Column(
            'notification_unavailable_body', sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
