"""notification rules replace per-honeypot subscriptions

Revision ID: 4edc297d7111
Revises: ae8e34a51aba
Create Date: 2026-09-14 07:35:45.776201

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4edc297d7111'
down_revision: str | None = 'ae8e34a51aba'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

# `notification_channel` already exists (created by ae8e34a51aba, for
# `honeypot_notification_subscriptions.delivery_channel`/
# `notification_logs.channel`) — reused here for `notification_rules.
# delivery_channel` with `create_type=False`, same pattern as that
# migration's own reuse. `notification_scope` is new to this migration.
_notification_channel_enum = postgresql.ENUM(
    "email", "webhook", name="notification_channel", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: reuse the
    # existing `notification_channel` enum type instead of creating it
    # again, and wrap to this project's 100-col limit. ###
    op.create_table(
        'notification_rules',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'scope', sa.Enum('company', 'honeypot', name='notification_scope'), nullable=False
        ),
        sa.Column('company_id', sa.Uuid(), nullable=True),
        sa.Column('honeypot_id', sa.Uuid(), nullable=True),
        sa.Column('delivery_channel', _notification_channel_enum, nullable=False),
        sa.Column('target_email', sa.String(length=255), nullable=True),
        sa.Column('webhook_url', sa.String(length=1000), nullable=True),
        sa.Column('notify_on_alert', sa.Boolean(), nullable=False),
        sa.Column('notify_on_unavailable', sa.Boolean(), nullable=False),
        sa.Column('unavailable_after_minutes', sa.Integer(), nullable=False),
        sa.Column('notify_on_recovered', sa.Boolean(), nullable=False),
        sa.Column('recovered_after_minutes', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['company_id'],
            ['companies.id'],
            name=op.f('fk_notification_rules_company_id_companies'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['honeypot_id'],
            ['honeypots.id'],
            name=op.f('fk_notification_rules_honeypot_id_honeypots'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_notification_rules_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_rules')),
    )
    op.create_index(
        op.f('ix_notification_rules_company_id'), 'notification_rules', ['company_id'], unique=False
    )
    op.create_index(
        op.f('ix_notification_rules_honeypot_id'),
        'notification_rules',
        ['honeypot_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_notification_rules_user_id'), 'notification_rules', ['user_id'], unique=False
    )
    op.create_table(
        'notification_rule_states',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('rule_id', sa.Uuid(), nullable=False),
        sa.Column('honeypot_id', sa.Uuid(), nullable=False),
        sa.Column('unavailable_notified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('recovered_notified_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['honeypot_id'],
            ['honeypots.id'],
            name=op.f('fk_notification_rule_states_honeypot_id_honeypots'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['rule_id'],
            ['notification_rules.id'],
            name=op.f('fk_notification_rule_states_rule_id_notification_rules'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_rule_states')),
        sa.UniqueConstraint(
            'rule_id', 'honeypot_id', name='uq_notification_rule_state_rule_honeypot'
        ),
    )
    op.create_index(
        op.f('ix_notification_rule_states_honeypot_id'),
        'notification_rule_states',
        ['honeypot_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_notification_rule_states_rule_id'),
        'notification_rule_states',
        ['rule_id'],
        unique=False,
    )
    op.drop_index(
        op.f('ix_honeypot_notification_subscriptions_honeypot_id'),
        table_name='honeypot_notification_subscriptions',
    )
    op.drop_index(
        op.f('ix_honeypot_notification_subscriptions_user_id'),
        table_name='honeypot_notification_subscriptions',
    )
    op.drop_table('honeypot_notification_subscriptions')
    op.add_column(
        'honeypots', sa.Column('reachable_since', sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honeypots', 'reachable_since')
    op.create_table(
        'honeypot_notification_subscriptions',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('honeypot_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('notify_on_alert', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('notify_on_unavailable', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('unavailable_after_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'unavailable_notified_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'delivery_channel',
            _notification_channel_enum,
            server_default=sa.text("'email'::notification_channel"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('webhook_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ['honeypot_id'],
            ['honeypots.id'],
            name=op.f('fk_honeypot_notification_subscriptions_honeypot_id_honeypots'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_honeypot_notification_subscriptions_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_notification_subscriptions')),
        sa.UniqueConstraint(
            'user_id',
            'honeypot_id',
            name=op.f('uq_honeypot_notification_subscription_user_honeypot'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f('ix_honeypot_notification_subscriptions_user_id'),
        'honeypot_notification_subscriptions',
        ['user_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_honeypot_notification_subscriptions_honeypot_id'),
        'honeypot_notification_subscriptions',
        ['honeypot_id'],
        unique=False,
    )
    op.drop_index(
        op.f('ix_notification_rule_states_rule_id'), table_name='notification_rule_states'
    )
    op.drop_index(
        op.f('ix_notification_rule_states_honeypot_id'), table_name='notification_rule_states'
    )
    op.drop_table('notification_rule_states')
    op.drop_index(op.f('ix_notification_rules_user_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_honeypot_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_company_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.execute("DROP TYPE IF EXISTS notification_scope")
    # ### end Alembic commands ###
