"""add netbird hostname to app settings

Revision ID: 5ce48ec7720d
Revises: ab82289f9318
Create Date: 2026-09-17 09:11:42.524113

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ce48ec7720d"
down_revision: str | None = "ab82289f9318"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_settings", sa.Column("netbird_hostname", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "netbird_hostname")
    # ### end Alembic commands ###
