"""notification webhook, history, log retention

Revision ID: ae8e34a51aba
Revises: ecbd56bc810b
Create Date: 2026-09-14 06:33:11.357894

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae8e34a51aba'
down_revision: str | None = 'ecbd56bc810b'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

# `notification_channel` is used by both `notification_logs.channel` (a
# brand-new table, whose own CREATE TABLE creates the enum type the first
# time) and `honeypot_notification_subscriptions.delivery_channel` (an
# existing table's new column, added right after) — the second reference
# must use `create_type=False`, or Postgres fails with "type
# notification_channel already exists". Same pattern already used
# elsewhere in this project for a type shared across two columns/tables
# (see alembic/versions/a1b2c3d4e5f6_add_company_syslog.py's
# `syslog_protocol`), just within one migration here instead of two.
_notification_channel_enum = postgresql.ENUM(
    "email", "webhook", name="notification_channel", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: reuse the
    # `notification_channel` enum type instead of creating it twice, give
    # `delivery_channel` a server default so adding it as NOT NULL is safe
    # against existing subscription rows (upgrade safety — see CLAUDE.md's
    # checklist), and wrap to this project's 100-col limit. ###
    op.create_table(
        'notification_logs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('honeypot_id', sa.Uuid(), nullable=True),
        sa.Column(
            'kind',
            sa.Enum('alert', 'unavailable', 'recovered', 'test', name='notification_kind'),
            nullable=False,
        ),
        sa.Column(
            'channel', sa.Enum('email', 'webhook', name='notification_channel'), nullable=False
        ),
        sa.Column('target', sa.String(length=500), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('is_test', sa.Boolean(), nullable=False),
        sa.Column('honeypot_name', sa.String(length=255), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['honeypot_id'],
            ['honeypots.id'],
            name=op.f('fk_notification_logs_honeypot_id_honeypots'),
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_notification_logs_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs')),
    )
    op.create_index(
        op.f('ix_notification_logs_honeypot_id'), 'notification_logs', ['honeypot_id'], unique=False
    )
    op.create_index(
        op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False
    )
    op.add_column(
        'app_settings', sa.Column('notification_log_retention_days', sa.Integer(), nullable=True)
    )
    op.add_column(
        'honeypot_notification_subscriptions',
        sa.Column(
            'delivery_channel',
            _notification_channel_enum,
            nullable=False,
            server_default='email',
        ),
    )
    op.add_column(
        'honeypot_notification_subscriptions',
        sa.Column('webhook_url', sa.String(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honeypot_notification_subscriptions', 'webhook_url')
    op.drop_column('honeypot_notification_subscriptions', 'delivery_channel')
    op.drop_column('app_settings', 'notification_log_retention_days')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_honeypot_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.execute("DROP TYPE IF EXISTS notification_channel")
    op.execute("DROP TYPE IF EXISTS notification_kind")
    # ### end Alembic commands ###
